### PR TITLE
Optimize udmpparser::UserDumpParser::GetMemBlock

### PR DESCRIPTION
**Pull request by 0-x-2-2**
It works in my testing, let me know if you can find any issues with it. This is significantly faster, has worked in my tooling, and has sped up IAT resolving from 5028ms to 24ms on my machine in my application when profiled.

### CODE REVIEW

**Comment by 0vercl0k** [comment]
Oof great find - thank you for diagnosing the issue and taking the time to send a PR 🙏🏽

Let me work off this PR to fix the CI & update how the Python wheels gets generated.. shouldn't take me too long.

Cheers

**Comment by 0vercl0k** [comment]
Actually, isn't this a bug `if (it != Mem_.begin()) {` ? Shouldn't it be `Mem_.end()` @0-x-2-2 or I am missing something?

**Comment by 0vercl0k** [comment]
Okay never mind, I read that piece of code too fast - my apologies 😅

Cheers

**Comment by 0vercl0k** [comment]
All right, if this looks good to you I'll get this merged this weekend 🙂 thank you again!

Cheers

**Comment by 0-x-2-2** [comment]
looks good :)

**Comment by 0vercl0k** [comment]
Haha awesome - to be fair, you diagnosed the problem as well :)

In any case, thank you again; let's merge this and will keep the thread updated when the Python wheels are up.

Cheers

**Comment by 0vercl0k** [comment]
Okay, [v0.6](https://pypi.org/project/udmp-parser/0.6.0/) has been published on pypi:

```
>pip install udmp_parser
Requirement already satisfied: udmp_parser in c:\users\over\anaconda3\lib\site-packages (0.6.0)
```

```
over@panther:~$ pip install udmp_parser
Defaulting to user installation because normal site-packages is not writeable
Collecting udmp_parser
  Downloading udmp_parser-0.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Downloading udmp_parser-0.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (235 kB)
Installing collected packages: udmp_parser
Successfully installed udmp_parser-0.6.0
```

**Comment by 0-x-2-2** [comment]
Thanks.

**Pull request merged**
