### PR TITLE
Integrate minidump generate to `udmp_parser` module + PYI definitions

### LINKED ISSUE #12: Add type hints (`.pyi` file) for the python bindings
Would be really nice to have because it gives you proper autocomplete from VSCode/PyCharm out of the box.

### PR DESCRIPTION
**Pull request by hugsy**
This PR:
 - separate `udmp_parser.utils` to a dedicated file, and extends it by adding a `generate_minidump` function. A variant of this function is added to the `pyproject.toml::project.scripts` in order to allow automatically generating a .exe when `pip install`-ing it, making this a lot more convenient + scriptable
 - fixes #12 , originally by using `nanobind-stugen` which failed miserably. Then my OCD took over so I completed it all.
 - Fixes one missing class (`MemoryInfoListStream_t` -> `MemoryInfoListStream`) which I forgot to expose during my former PR.

### CODE REVIEW

**Comment by 0vercl0k** [comment]
Woot, looks awesome 😮🙏🏽!

Give me a few days to review this 😊

Cheers

**Comment by 0vercl0k** [comment]
All right I did a pass and cleaned up a few things:
- I bumped from v4 to v5 as it seems one of the field/type has a new name so I assumed it is a breaking change
- Ran the black formatter on the ipy stubs

Watchu think 🙈?

Cheers

**Comment by hugsy** [comment]
> Watchu think 🙈?

Awesome! All for good for me, sorry I completely forgot to pass `black` on it 🤦 

> Also what's the project.scripts entry do?

It's a convenient way to have the [packager generate an executable](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#entry-points-and-automatic-script-creation) - .sh on Lin/Mac, .exe on Win - directly on installation. The "bin" is automatically placed into the `~/.local/bin` (resp. `%AppData%\Roaming\Python\PythonXXX\Scripts`). 
image

**Comment by 0vercl0k** [comment]
That's awesome!

Took another look at this today - do you know if we need special handling for the pyi files? As far as I can tell they don't get included in the wheel so I'm not quite sure how they are supposed to be shipped?

Maybe I'm missing something!

Cheers

**Comment by hugsy** [comment]
> Took another look at this today - do you know if we need special handling for the pyi files? As far as I can tell they don't get included in the wheel so I'm not quite sure how they are supposed to be shipped?

The structure of the wheel is defined (in our case) by the CMakeLists.txt so everything is magically done for you using [this cmake install directive](https://github.com/hugsy/udmp-parser/blob/63506db6fe9933e8333a78f225c341d1ea1051ab/src/python/CMakeLists.txt#L41) which will install the folder according to [PEP 561](https://peps.python.org/pep-0561/) - i.e. `$package_name-stubs/`. Any modern IDE which respects the PEP will automatically load the signatures from the PYIs. 
image
image

Since you don't have anything but the `pyd` to install, I went with the [stub-only package approach](https://peps.python.org/pep-0561/#stub-only-packages). But this is choice and if you think at some point you'll want to also include your own pure Python code, you can change it to [partial package](https://peps.python.org/pep-0561/#partial-stub-packages) format. 

Hope this clarifies.
LMK if anything is not clear enough 😉

**Comment by 0vercl0k** [comment]
To clarify, this means people need to `cmake` install it themselves vs just `pip install`?

**Comment by hugsy** [comment]
> To clarify, this means people need to cmake install it themselves vs just pip install?

If they install from the source (i.e. `pip install .`), cmake will build it yes.

If they install from a wheel or pypi, no, everything is already part of the .whl
image

**Comment by 0vercl0k** [comment]
Ok never mind, I am an idiot - I was building this wheel, but inspecting an older version 🤦🏽‍♂️

**Comment by 0vercl0k** [comment]
All right I think it looks great, thanks again @hugsy 🔥

**Comment by 0vercl0k** [comment]
All right, I pushed out the v0.5.0: https://pypi.org/project/udmp-parser/0.5.0/ / https://github.com/0vercl0k/udmp-parser/releases/tag/v0.5.0 -- let me know if I missed something 🫡

**Comment by hugsy** [comment]
Just tested, seems to be working great !
Thanks for the review & merge 😉

**Pull request merged**
